#pragma checksum "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "623a1539e2360f00ee4db2b707e7c112289a0384"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Details), @"mvc.1.0.view", @"/Views/Home/Details.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\_ViewImports.cshtml"
using Bacchus;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\_ViewImports.cshtml"
using Bacchus.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"623a1539e2360f00ee4db2b707e7c112289a0384", @"/Views/Home/Details.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"23e35542043c2c3bd19c52b83b68b5e40825f686", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Details : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<Bacchus.Models.Product>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("runat", new global::Microsoft.AspNetCore.Html.HtmlString("server"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("form1"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("onload", new global::Microsoft.AspNetCore.Html.HtmlString("timeFunc()"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line 3 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
  
    ViewData["Title"] = "Details";
    DateTime endTime = DateTime.Parse(Model.biddingEndDate);

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n");
#nullable restore
#line 8 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
Write(Html.HiddenFor(model => model.productId));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<dt class=\"col-sm-10\">\r\n    ");
#nullable restore
#line 10 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
Write(Html.DisplayNameFor(model => model.productName));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n</dt>\r\n<dd class=\"col-sm-10\">\r\n    ");
#nullable restore
#line 13 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
Write(Html.DisplayFor(model => model.productName));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n</dd>\r\n\r\n<dt class=\"col-sm-2\">\r\n    ");
#nullable restore
#line 17 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
Write(Html.DisplayNameFor(model => model.productDescription));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n</dt>\r\n<dd class=\"col-sm-10\">\r\n    ");
#nullable restore
#line 20 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
Write(Html.DisplayFor(model => model.productDescription));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n</dd>\r\n\r\n<dt class=\"col-sm-2\">\r\n    ");
#nullable restore
#line 24 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
Write(Html.DisplayNameFor(model => model.productCategory));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n</dt>\r\n<dd class=\"col-sm-10\">\r\n    ");
#nullable restore
#line 27 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
Write(Html.DisplayFor(model => model.productCategory));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n    ");
#nullable restore
#line 28 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
Write(DateTime.Parse(Model.biddingEndDate));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n</dd>\r\n\r\n<dt class=\"col-sm-10\">\r\n    ");
#nullable restore
#line 32 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
Write(Html.DisplayNameFor(model => model.biddingEndDate));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n</dt>\r\n<dd class=\"col-sm-10\">\r\n    ");
#nullable restore
#line 35 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
Write(DateTime.Parse(Model.biddingEndDate).ToString("dddd, dd MMMM yyyy HH:mm:ss"));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n</dd>\r\n\r\n<dd class=\"col-sm-10\">\r\n    <html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n    ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("head", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "623a1539e2360f00ee4db2b707e7c112289a03847760", async() => {
                WriteLiteral("\r\n        <title></title>\r\n        <script type=\"text/javascript\">\r\n\r\n            var tim;\r\n            \r\n            var interval = \'");
#nullable restore
#line 46 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
                       Write(endTime.Subtract(DateTime.Now).TotalSeconds);

#line default
#line hidden
#nullable disable
                WriteLiteral(@"';

            function timeFunc() {
                showTime();
            }

            function showTime() {
                var minutes = Math.floor(interval / 60);
                var seconds = Math.floor(interval % 60);
                if (interval <= 0) {
                    document.getElementById(""showtime"").innerHTML = ""Auction is over"";
                    document.getElementById(""showtime"").style.color = ""red"";
                    clearTimeout(tim);
                }
                else {

                    if (seconds < 10) {
                        document.getElementById(""showtime"").innerHTML = minutes + "":"" + ""0"" + seconds;
                        interval = parseInt(interval) - 1;
                        tim = setTimeout(""showTime()"", 1000);
                    }
                    else {
                        document.getElementById(""showtime"").innerHTML = minutes + "":"" + seconds;
                        interval = parseInt(interval) - 1;
                    ");
                WriteLiteral("    tim = setTimeout(\"showTime()\", 1000);\r\n                    }\r\n                }\r\n            }\r\n        </script>\r\n    ");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n\r\n    ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("body", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "623a1539e2360f00ee4db2b707e7c112289a038410444", async() => {
                WriteLiteral("\r\n        ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "623a1539e2360f00ee4db2b707e7c112289a038410711", async() => {
                    WriteLiteral(@"
            <div>
                <table width=""100%"" align=""center"">
                    <tr>
                        <td colspan=""2"">
                            <h3> <div id=""showtime""></div> </h3>
                        </td>
                    </tr>
                </table>

            </div>
        ");
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
                __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n    ");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n    </html>\r\n</dd>\r\n\r\n\r\n");
#nullable restore
#line 95 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
 using (Html.BeginForm())
{

    

#line default
#line hidden
#nullable disable
#nullable restore
#line 98 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
Write(Html.AntiForgeryToken());

#line default
#line hidden
#nullable disable
#nullable restore
#line 100 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

#line default
#line hidden
#nullable disable
#nullable restore
#line 101 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
Write(Html.HiddenFor(model => model.productId));

#line default
#line hidden
#nullable disable
            WriteLiteral("    <div class=\"form-group\">\r\n        ");
#nullable restore
#line 104 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
   Write(Html.LabelFor(model => model.lastBidderName, htmlAttributes: new { @class = "control-label col-md-4" }));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        <div class=\"col-md-10\">\r\n            ");
#nullable restore
#line 106 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
       Write(Html.EditorFor(model => model.lastBidderName, new { htmlAttributes = new { @class = "form-control col-md-4" } }));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            ");
#nullable restore
#line 107 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
       Write(Html.ValidationMessageFor(model => model.lastBidderName, "", new { @class = "text-danger" }));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </div>\r\n    </div>\r\n");
            WriteLiteral("    <div class=\"form-group\">\r\n        ");
#nullable restore
#line 112 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
   Write(Html.LabelFor(model => model.lastBidderSum, htmlAttributes: new { @class = "control-label col-md-4" }));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        <div class=\"col-md-10\">\r\n            ");
#nullable restore
#line 114 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
       Write(Html.EditorFor(model => model.lastBidderSum, new { htmlAttributes = new { @class = "form-control col-md-4" } }));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            ");
#nullable restore
#line 115 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
       Write(Html.ValidationMessageFor(model => model.lastBidderSum, "", new { @class = "text-danger" }));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </div>\r\n    </div>\r\n");
            WriteLiteral("    <div class=\"form-group\">\r\n        <div class=\"col-md-offset-2 col-md-10\">\r\n            <input type=\"submit\" value=\"Make a bid\" class=\"btn btn-primary\" />\r\n        </div>\r\n    </div>\r\n");
#nullable restore
#line 124 "C:\Users\local user\source\repos\Bacchus\Bacchus\Views\Home\Details.cshtml"
}

#line default
#line hidden
#nullable disable
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<Bacchus.Models.Product> Html { get; private set; }
    }
}
#pragma warning restore 1591
